// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXSampleWeb
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIXSampleWeb.331874eb-c50e-4110-bd68-82f52bfb0b73";
        public const string Name = "VSIXSampleWeb";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Gilles Guimard";
        public const string Tags = "";
    }
}
